# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class XinLang_KouBei(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    url = scrapy.Field()
    id = scrapy.Field()
    sub_brand_id = scrapy.Field()
    sum_score = scrapy.Field()
    sample_size = scrapy.Field()
    space_score = scrapy.Field()
    power_scoure = scrapy.Field()
    control_score = scrapy.Field()
    fuel_consumption_score = scrapy.Field()
    comfort_score = scrapy.Field()
    exterior_score = scrapy.Field()
    interior_score = scrapy.Field()
    cost_performance_score = scrapy.Field()
    create_at = scrapy.Field()
    paiming = scrapy.Field()
    pic = scrapy.Field()
    level = scrapy.Field()


class XinLang_XiaoShou(scrapy.Item):
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    url = scrapy.Field()
    id = scrapy.Field()
    name = scrapy.Field()
    pic = scrapy.Field()
    sales_volume = scrapy.Field()
    paiming = scrapy.Field()
    last_paiming = scrapy.Field()
    max_sales_month = scrapy.Field()
    isupper = scrapy.Field()
    year_sales_volume = scrapy.Field()
    list = scrapy.Field()
    level = scrapy.Field()
    # url = scrapy.Field()
    # url = scrapy.Field()
    # url = scrapy.Field()


class XinLang_CheXing(scrapy.Item):
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    url = scrapy.Field()
    rank = scrapy.Field()
    slvalue = scrapy.Field()
    serialId = scrapy.Field()
    serialName = scrapy.Field()
    pic = scrapy.Field()
    whitePic = scrapy.Field()
    preSlvalue = scrapy.Field()
    changeSign = scrapy.Field()
    changeValue = scrapy.Field()
    level = scrapy.Field()
    endDay = scrapy.Field()
    startDay = scrapy.Field()
    week = scrapy.Field()
    year = scrapy.Field()
    zhishu = scrapy.Field()


class XinLang_PinPai(scrapy.Item):
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    endDay = scrapy.Field()
    startDay = scrapy.Field()
    week = scrapy.Field()
    year = scrapy.Field()
    zhishu = scrapy.Field()
    brandId = scrapy.Field()
    brandName = scrapy.Field()
    changeSign = scrapy.Field()
    changeValue = scrapy.Field()
    pic = scrapy.Field()
    preSlvalue = scrapy.Field()
    rank = scrapy.Field()
    slvalue = scrapy.Field()
    whitePic = scrapy.Field()
    url = scrapy.Field()


class XinLang_XiaoLiang(scrapy.Item):
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    url = scrapy.Field()
    sales_month = scrapy.Field()
    sales_year = scrapy.Field()
    transaction_price = scrapy.Field()
    chenjiao_val = scrapy.Field()
    xiaoliang_val = scrapy.Field()
    zonghe_rank = scrapy.Field()
    anquan_rank = scrapy.Field()
    xingneng_rank = scrapy.Field()
    youhao_rank = scrapy.Field()
    kongjian_rank = scrapy.Field()
    shushi_rank = scrapy.Field()
    renji_rank = scrapy.Field()
    contend_car = scrapy.Field()
    series = scrapy.Field()
    series_url = scrapy.Field()
    brand_name = scrapy.Field()


class Autohome_price(scrapy.Item):
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    brand = scrapy.Field()
    url = scrapy.Field()
    factory = scrapy.Field()
    series = scrapy.Field()
    pinfen = scrapy.Field()
    price = scrapy.Field()
    kongjian = scrapy.Field()
    dongli = scrapy.Field()
    caokong = scrapy.Field()
    youhao = scrapy.Field()
    shushixing = scrapy.Field()
    waiguan = scrapy.Field()
    neishi = scrapy.Field()
    xingjiabi = scrapy.Field()


class Autohome_price1(scrapy.Item):
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    brand = scrapy.Field()
    url = scrapy.Field()
    factory = scrapy.Field()
    series = scrapy.Field()
    pinfen = scrapy.Field()
    price = scrapy.Field()
    kongjian = scrapy.Field()
    dongli = scrapy.Field()
    caokong = scrapy.Field()
    youhao = scrapy.Field()
    shushixing = scrapy.Field()
    waiguan = scrapy.Field()
    neishi = scrapy.Field()
    xingjiabi = scrapy.Field()


class Autohome_depreciate(scrapy.Item):
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    url = scrapy.Field()
    series = scrapy.Field()
    level = scrapy.Field()
    fudu = scrapy.Field()
    price = scrapy.Field()


class xinlang_koubei_content(scrapy.Item):
    statusplus = scrapy.Field()
    grad_time = scrapy.Field()
    url = scrapy.Field()
    zhName = scrapy.Field()
    brandid = scrapy.Field()
    fenxi = scrapy.Field()
    serialName = scrapy.Field()
    serialLevel = scrapy.Field()
    sellStatus = scrapy.Field()
    serialId = scrapy.Field()
    autoType = scrapy.Field()
    guidePrice = scrapy.Field()
    corpId = scrapy.Field()
    corpName = scrapy.Field()
    support_num = scrapy.Field()
    reply_num = scrapy.Field()
    postedtime = scrapy.Field()
    content = scrapy.Field()
    title = scrapy.Field()
    koubei_bang = scrapy.Field()
    # url = scrapy.Field()
    # url = scrapy.Field()
    # url = scrapy.Field()
    # url = scrapy.Field()


class Autohome_koubei_all(scrapy.Item):
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    posted_time = scrapy.Field()
    support_num = scrapy.Field()
    browse_num = scrapy.Field()
    comment_num = scrapy.Field()
    brand = scrapy.Field()
    factory = scrapy.Field()
    series = scrapy.Field()
    car_model = scrapy.Field()
    user = scrapy.Field()
    title = scrapy.Field()
    content = scrapy.Field()
    bad_msg = scrapy.Field()
    url = scrapy.Field()
    city = scrapy.Field()
    # url = scrapy.Field()
    # url = scrapy.Field()
    # url = scrapy.Field()


class LuntanItem(scrapy.Item):
    # define the fields for your item here like:
    grabtime = scrapy.Field()  # 抓取时间
    parsetime = scrapy.Field()  # 解析时间
    content = scrapy.Field()
    url = scrapy.Field()
    user_name = scrapy.Field()
    posted_time = scrapy.Field()
    user_car = scrapy.Field()
    province = scrapy.Field()
    region = scrapy.Field()
    click_num = scrapy.Field()
    reply_num = scrapy.Field()
    title = scrapy.Field()
    content_num = scrapy.Field()
    statusplus = scrapy.Field()
    information_source = scrapy.Field()
    brand = scrapy.Field()


class Autohome_newcar(scrapy.Item):
    statusplus = scrapy.Field()
    grade_time = scrapy.Field()
    posted_time = scrapy.Field()
    url = scrapy.Field()
    car = scrapy.Field()


class Autohome_jiangjia(scrapy.Item):
    statusplus = scrapy.Field()
    grade_time = scrapy.Field()
    url = scrapy.Field()
    MaxOriginalPrice = scrapy.Field()
    MaxPriceOff = scrapy.Field()
    MaxPriceOffSpecId = scrapy.Field()
    MinOriginalPrice = scrapy.Field()
    SeriesId = scrapy.Field()
    SeriesImg = scrapy.Field()
    SpecNumber = scrapy.Field()
    SeriesName = scrapy.Field()


class Autohome_pingfen(scrapy.Item):
    statusplus = scrapy.Field()
    grade_time = scrapy.Field()
    brand = scrapy.Field()
    car_series = scrapy.Field()
    car_model = scrapy.Field()
    total_score = scrapy.Field()
    space = scrapy.Field()
    power = scrapy.Field()
    manipulation = scrapy.Field()
    fuel_consumption = scrapy.Field()
    comfortability = scrapy.Field()
    appearance = scrapy.Field()
    interior_trim = scrapy.Field()
    cost_performance = scrapy.Field()
    url = scrapy.Field()


class Autohome_pingfen_for_home(scrapy.Item):
    statusplus = scrapy.Field()
    autohomeid = scrapy.Field()
    dealer_price = scrapy.Field()
    grab_time = scrapy.Field()
    brand = scrapy.Field()
    car_series = scrapy.Field()
    car_model = scrapy.Field()
    total_score = scrapy.Field()
    space = scrapy.Field()
    power = scrapy.Field()
    manipulation = scrapy.Field()
    fuel_consumption = scrapy.Field()
    comfortability = scrapy.Field()
    appearance = scrapy.Field()
    interior_trim = scrapy.Field()
    cost_performance = scrapy.Field()
    url = scrapy.Field()


class xinlang_pingfen(scrapy.Item):
    statusplus = scrapy.Field()
    grade_time = scrapy.Field()
    brand = scrapy.Field()
    car_series = scrapy.Field()
    car_model = scrapy.Field()
    total_score = scrapy.Field()
    space = scrapy.Field()
    power = scrapy.Field()
    manipulation = scrapy.Field()
    fuel_consumption = scrapy.Field()
    comfortability = scrapy.Field()
    appearance = scrapy.Field()
    interior_trim = scrapy.Field()
    cost_performance = scrapy.Field()
    car_space = scrapy.Field()
    car_power = scrapy.Field()
    car_manipulation = scrapy.Field()
    car_fuel_consumption = scrapy.Field()
    car_comfortability = scrapy.Field()
    car_appearance = scrapy.Field()
    car_interior_trim = scrapy.Field()
    car_cost_performance = scrapy.Field()
    user = scrapy.Field()
    url = scrapy.Field()


class lianjia(scrapy.Item):
    small_area = scrapy.Field()
    area = scrapy.Field()
    big_area = scrapy.Field()
    url = scrapy.Field()
    price = scrapy.Field()
    title = scrapy.Field()
    address = scrapy.Field()
    desc = scrapy.Field()
    unit_price = scrapy.Field()
    posted_time = scrapy.Field()
    grad_time = scrapy.Field()
    statusplus = scrapy.Field()
class LianlianItem(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    payment = scrapy.Field()
    operatorLogo = scrapy.Field()
    operatorId = scrapy.Field()
    operatorName = scrapy.Field()
    stationId = scrapy.Field()
    stationName = scrapy.Field()
    electricityFee = scrapy.Field()
    distance = scrapy.Field()
    directTotal = scrapy.Field()
    directAvaliable = scrapy.Field()
    alternatingTotal = scrapy.Field()
    alternatingAvaliable = scrapy.Field()
    parkFee = scrapy.Field()
    serviceFee = scrapy.Field()
    stationLng = scrapy.Field()
    stationLat = scrapy.Field()
    stationLngBD = scrapy.Field()
    stationLatBD = scrapy.Field()
    stationType = scrapy.Field()
    address = scrapy.Field()
    pictures = scrapy.Field()
    sitePicUrl = scrapy.Field()
    status2 = scrapy.Field()

class echongdianItem(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    adImages= scrapy.Field()
    address = scrapy.Field()
    businessTime = scrapy.Field()
    chargerNumAC = scrapy.Field()
    chargerNumDC= scrapy.Field()
    chargerNumFast = scrapy.Field()
    chargerNumSlow = scrapy.Field()
    chargerNumSuper = scrapy.Field()
    chargerQuantity= scrapy.Field()
    chargerTypeStatusAC = scrapy.Field()
    chargerTypeStatusDC= scrapy.Field()
    chargingFee= scrapy.Field()
    cityCode = scrapy.Field()
    cityName= scrapy.Field()
    currentType = scrapy.Field()
    favorite = scrapy.Field()
    hardwareType= scrapy.Field()
    id = scrapy.Field()
    inGs = scrapy.Field()
    isCheckIn = scrapy.Field()
    lat = scrapy.Field()
    link= scrapy.Field()
    lng = scrapy.Field()
    lowerPower= scrapy.Field()
    mapIcon = scrapy.Field()
    name = scrapy.Field()
    numberOfComments= scrapy.Field()
    # "******************"
    operatorInfos= scrapy.Field()
    operatorTypes = scrapy.Field()
    parkingAreaCount = scrapy.Field()
    parkingFee = scrapy.Field()
    payType = scrapy.Field()
    payTypeDesc = scrapy.Field()
    phone= scrapy.Field()
    priceRational= scrapy.Field()
    propertyType = scrapy.Field()
    province= scrapy.Field()
    score = scrapy.Field()
    serviceCode = scrapy.Field()
    serviceDesc = scrapy.Field()
    serviceFee = scrapy.Field()
    standard = scrapy.Field()
    # 11111111111111111
    stationImages = scrapy.Field()
    stationNotice = scrapy.Field()
    stationType = scrapy.Field()
    status = scrapy.Field()
    supportCharge= scrapy.Field()
    upperPower = scrapy.Field()
    urposeType = scrapy.Field()